// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckKey(arg1) {
  return window['go']['main']['App']['CheckKey'](arg1);
}

export function Configure(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Configure'](arg1, arg2, arg3, arg4, arg5);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function OpenDashboard() {
  return window['go']['main']['App']['OpenDashboard']();
}

export function OpenRepo() {
  return window['go']['main']['App']['OpenRepo']();
}

export function OpenUpdate(arg1) {
  return window['go']['main']['App']['OpenUpdate'](arg1);
}

export function Restore(arg1) {
  return window['go']['main']['App']['Restore'](arg1);
}

export function RevealBackupDir() {
  return window['go']['main']['App']['RevealBackupDir']();
}
