// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {brewkeg} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CheckKey(arg1:string):Promise<brewkeg.KeyCheck>;

export function Configure(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:string,arg6:string):Promise<main.ConfigureResult>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetState():Promise<main.State>;

export function OpenDashboard():Promise<void>;

export function OpenRepo():Promise<void>;

export function OpenUpdate(arg1:string):Promise<void>;

export function RefreshSpec():Promise<brewkeg.Spec>;

export function Reset(arg1:boolean):Promise<main.ResetResult>;

export function Restore(arg1:string):Promise<string>;

export function RevealBackupDir():Promise<void>;
