// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckForUpdateFromMenu() {
  return window['go']['main']['App']['CheckForUpdateFromMenu']();
}

export function CheckKey(arg1) {
  return window['go']['main']['App']['CheckKey'](arg1);
}

export function ClearDevMode() {
  return window['go']['main']['App']['ClearDevMode']();
}

export function Configure(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Configure'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function OpenDashboard() {
  return window['go']['main']['App']['OpenDashboard']();
}

export function OpenRepo() {
  return window['go']['main']['App']['OpenRepo']();
}

export function OpenUpdate(arg1) {
  return window['go']['main']['App']['OpenUpdate'](arg1);
}

export function RefreshSpec() {
  return window['go']['main']['App']['RefreshSpec']();
}

export function Reset(arg1) {
  return window['go']['main']['App']['Reset'](arg1);
}

export function ResetFromMenu() {
  return window['go']['main']['App']['ResetFromMenu']();
}

export function Restore(arg1) {
  return window['go']['main']['App']['Restore'](arg1);
}

export function RevealBackupDir() {
  return window['go']['main']['App']['RevealBackupDir']();
}

export function SetDevBaseURL(arg1) {
  return window['go']['main']['App']['SetDevBaseURL'](arg1);
}

export function SetDevMode(arg1) {
  return window['go']['main']['App']['SetDevMode'](arg1);
}

export function TestGateway() {
  return window['go']['main']['App']['TestGateway']();
}

export function ToggleDevModeFromMenu() {
  return window['go']['main']['App']['ToggleDevModeFromMenu']();
}
